"""
PDF Generation Utility — LexisCo
Converts generated legal document text into a downloadable PDF file.
"""

from fpdf import FPDF
import io
from loguru import logger

class LegalPDF(FPDF):
    def header(self):
        # Professional legal header can be added here
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'LexisCo - AI Legal Assistant', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by LexisCo AI', 0, 0, 'C')

def create_legal_pdf(content: str) -> io.BytesIO:
    """
    Converts a legal document string into a PDF byte stream.
    """
    try:
        pdf = LegalPDF()
        pdf.add_page()
        
        # Set primary font
        pdf.set_font("helvetica", size=12)
        
        # Helper to clean text for Latin-1 (FPDF limitation)
        # Replacing common problematic characters from LLM output
        clean_text = content.replace('’', "'").replace('‘', "'").replace('“', '"').replace('”', '"').replace('–', '-')
        
        # Fallback for truly non-latin characters
        safe_text = clean_text.encode('latin-1', 'replace').decode('latin-1')
        
        # Write content with better spacing
        pdf.multi_cell(0, 8, txt=safe_text)
        
        # Output to byte stream
        pdf_bytes = pdf.output()
        pdf_output = io.BytesIO(pdf_bytes)
        pdf_output.seek(0)
        
        return pdf_output
    except Exception as e:
        logger.error(f"PDF Generation Error: {e}")
        raise e
